### ISSUE TITLE
it does'nt start correctly

### ISSUE THREAD

**Issue by AlexLeGamer** [ESX-PUBLIC/esx_advanced_holdup#2]
when the server start i get this error:
`Error loading script server/main.lua in resource esx_advanced_holdup: server/main.lua:47: attempt to call a nil value (field 'Round')
stack traceback:
	server/main.lua:47: in function 'AddMoneyToBanks'
	server/main.lua:152: in main chunk
Failed to load script server/main.lua.
Started resource esx_advanced_holdup`
thanks to answer me as soon

**Comment by deviljin112** [comment]
You're probably running it without checking the config...

`BankToDeliver 		= "Legion Flecca Bank Vault",`

has to be changed to 

`BankToDeliver 		= "Fleeca Bank Vespucci Boulevard",`


Check my PR on original Repo :)

**Comment by AlexLeGamer** [comment]
i try to do what you told me but it does'nt change nothing

**Comment by HawaiiBeach** [comment]
Update ESX
