### ISSUE TITLE
Nil Value

### ISSUE THREAD

**Issue by Crainda** [ESX-PUBLIC/esx_advanced_holdup#3]
I'm trying this out, but when I start it I get the error Error Loading Script server/main.lua in resource esx_advanced_holdup: server/main.lua:47: attempt to call nil value (field 'Round')

Any idea how to fix this?

**Comment by Crainda** [comment]
I updated my ESX after reading the other post, but now it gives me a new error

 Error Loading Script server/main.lua in resource esx_advanced_holdup: server/main.lua:50: attempt to call nil value (field '?')

**Comment by delduwaht** [comment]
Fixed in https://github.com/ESX-PUBLIC/esx_advanced_holdup/commit/ead664024b667fa5022a6866cfb29f0afdbb3273
